name: atems
channels:
  - conda-forge
dependencies:
  - python=3.13
  - numpy
  - matplotlib
  - seaborn
  - pandas
  - scipy
  - ipython
  - jupyter
  - tqdm
  - scikit-image
  - opencv
  - pillow
  - tabulate
  - scikit-learn
  - albumentations
  - onnxruntime
