name: atems
channels:
  - conda-forge
dependencies:
  - python=3.13
  - numpy
  - matplotlib
  - seaborn
  - pandas
  - scipy
  - ipython
  - jupyter
  - tqdm
  - scikit-image
  - opencv
  - pillow
  - tabulate
  - scikit-learn
  - albumentations
  - onnxruntime
  - pip:
      - --extra-index-url https://download.pytorch.org/whl/cu128
      - torch==2.11.0+cu128
      - torchvision==0.26.0+cu128
      - segment-anything==1.0
      - micro-sam==1.8.12
